### PR TITLE
GCdocs updates

### PR DESCRIPTION
**Pull request by lchski**
Link to the GCdocs folder, and edit the English page’s metadata so it renders correctly.

### CODE REVIEW

**Comment by cmaczo** [comment]
Thanks so much, Lucas! 

Two things:
- Can you remove the _site directory changes from your PR? GH pages will automatically regenerate the site directory, so we should need to upload them again. 
- Any chance you can do the French version? I'm trying to update both languages simultaneously. If that seems to hard, no worries, but we need to make a plan for making the two pages the same.

**Comment by lchski** [comment]
On both counts: yes! Will work on the French.

Re: `_site`. Do you want the entire directory removed? It’s [already committed in `master`](https://github.com/cds-snc/design-research-handbook/tree/master/_site), but some files were missing (since the `.gitignore` was added a month ago)—this is why I’d manually committed the files from `_site`. See also #19.

**Comment by cmaczo** [comment]
Yes, we shouldn't have the _site directory in master at all. So feel free to munch it with this PR.

**Comment by lchski** [comment]
:+1: Ignored with the latest commit.

**Pull request merged**
