### PR TITLE
Create templates

### PR DESCRIPTION
**Pull request by marthaedwards**
Creating a new page for research templates

### CODE REVIEW

**Comment by cmaczo** [comment]
Thanks @marthaedwards! Could you add something like an `(under construction)` to each of the templates we don't have yet? Just don't want folks to be confused as to why the links aren't active.

**Comment by marthaedwards** [comment]
good suggestions @cmaczo I've updated the page

**Comment by cmaczo** [comment]
Thanks, Martha! Do we have the French version?

**Comment by adriannelee** [comment]
Hey Martha - I'm going to create the French page for this, btw! And add my usability testing template.

**Pull request merged**
