### PR TITLE
Create journal-de-bord.md

### PR DESCRIPTION
**Pull request by AntoineGarciaSuarez**
Description en francais du journal de bord.
First version of the "dairy studies" method

### CODE REVIEW

**Comment by cmaczo** [comment]
Thanks so much for taking the initiative to add this page, Antoine.

It's OK to add methods we haven't used historically to the handbook. No worries there.

**Comment by cmaczo** [comment]
However, a couple comments:

- [x] Can you make sure the headings match the other method pages? Each has a section called "Qu’est-ce X?", "Éléments clés des X", and "Ressources".
- [x]  Can you add a couple links to more resources? At least one link + one book is probably the minimum.
- [x]  After you've done another edit, can you send to translation for an English copy? We'll add that in at the same time.

Again, great job! Let me know if I can help.

**Comment by AntoineGarciaSuarez** [comment]
Sounds good! I’ll make the adjustments on Monday; happy to help😊
Enjoy your weekend!

**Comment by AntoineGarciaSuarez** [comment]
I've implemented the adjustments; let me know any others improvements !

**Comment by cmaczo** [comment]
Just a note that this PR is pending #12 -- we want to merge the English and French at the same time.

**Pull request merged**
